=== cantsaywisp1308/JavaAll/eclipe-workspace/Java/demo session 3/account.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="danhsachtaikhoan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="taikhoan" type="type_taikhoan" minOccurs="1" maxOccurs="unbounded">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="type_taikhoan">
        <xs:sequence>
            <xs:element name="username" type="type_username_ct"></xs:element>
            <xs:element name="password" type="type_password"></xs:element>
            <xs:element name="danhsachhoadon" type="type_danhsachhoadon"></xs:element>
        </xs:sequence>
        <xs:attribute name="ngaysinh" type="xs:date"></xs:attribute>
        <xs:attribute name="gioitinh" type="type_gioitinh"></xs:attribute>
    </xs:complexType>

<xs:simpleType name="type_username_ct">
    <xs:restriction base="xs:string">
        <xs:minLength value="6"></xs:minLength>
        <xs:maxLength value="10"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>    

<xs:simpleType name="type_gioitinh">
    <xs:restriction base="xs:string">
        <xs:enumeration value="nam"></xs:enumeration> 
        <xs:enumeration value="nu"></xs:enumeration> 
    </xs:restriction>
 </xs:simpleType>

<xs:simpleType name="type_password">
    <xs:restriction base="xs:string">
        <xs:minLength value="6"></xs:minLength>
        <xs:maxLength value="10"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="type_danhsachhoadon">
    <xs:sequence>
        <xs:element name="hoadon" type="type_hoadon"></xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="type_hoadon">
    <xs:sequence>
        <xs:element name="tenhd" type="xs:string"></xs:element>
        <xs:element name="ngaylap" type="type_ngaylap"></xs:element>
        <xs:element name="tinhtrang" type="type_tinhtrang"></xs:element>
        <xs:element name="httt" type="type_httt"></xs:element>
        <xs:element name="tongtien" >
                <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:double">
                                    <xs:attribute name="dvt" type="xs:string"></xs:attribute>
                            </xs:extension>  
                        </xs:simpleContent> 
                </xs:complexType>
        </xs:element>
        <xs:element name="chitiethoadon" type="type_chitiethoadon"></xs:element>
    </xs:sequence>
    <xs:attribute name="mahd" type="xs:string"></xs:attribute>
</xs:complexType>

<xs:complexType name="type_ngaylap">
    <xs:attribute name="dinhdang" type="xs:string"></xs:attribute>
</xs:complexType>

<xs:simpleType name="type_tinhtrang">
    <xs:restriction base="xs:string">
        <xs:enumeration value="da thanh toan"></xs:enumeration>
        <xs:enumeration value="chua thanh toan"></xs:enumeration>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="type_httt">
    <xs:restriction base="xs:string">
        <xs:enumeration value="tien mat"></xs:enumeration>
        <xs:enumeration value="chuyen khoan"></xs:enumeration>
        <xs:enumeration value="paypal"></xs:enumeration>
    </xs:restriction>
</xs:simpleType>




<xs:complexType name="type_chitiethoadon">
    <xs:sequence>
        <xs:element name="sanpham" type="type_sanpham" minOccurs="1" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="type_sanpham">
    <xs:sequence>
        <xs:element name="masp" type="xs:string"></xs:element>
        <xs:element name="tensp" type="xs:string"></xs:element>
        <xs:element name="gia" type="type_gia" ></xs:element>
        <xs:element name="soluong" type="type_soluong"></xs:element>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="type_gia">
    <xs:restriction base="xs:double">
        <xs:minExclusive value="0"></xs:minExclusive>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="type_soluong">
    <xs:restriction base="xs:int">
        <xs:minExclusive value="0"></xs:minExclusive>
    </xs:restriction>
</xs:simpleType>
</xs:schema>

=== cantsaywisp1308/JavaAll/eclipe-workspace/Java/demo session 3/accountList.xml
<?xml version="1.0" encoding="UTF-8"?>


<danhsachtaikhoan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="account.xsd">


    <taikhoan ngaysinh="1980-10-20" gioitinh="nam"> <!-- Ngay sinh kieu date, gioi tinh chon 1 trong 2 gia tri nam hoac nu -->
        <username>khang1024</username> <!-- Co it nhat 6 ki tu, toi da 10 ki tu, co 2 thuoc tinh min, max -->
        <password>123456789</password> <!-- Co it nhat 6 ki tu, toi da 10 ki tu -->
        <danhsachhoadon>
            <hoadon mahd="hd01"> <!-- Ma hoa don co it nhat 4 ki tu va toi da 6 ki tu -->
                <tenhd>Hoa don 1</tenhd>
                <ngaylap dinhdang="yyyy-MM-dd"></ngaylap> <!-- Kieu thoi gian co 1 thuoc tinh dindang -->
                <tinhtrang>da thanh toan</tinhtrang> <!-- Chon 1 trong 2 gia tri: da thanh toan hoa chua thanh toan -->
                <httt>tien mat</httt> <!-- Chon 1 trong 3 gia tri: tien mat, chuyen khoan hoac paypal -->
                <tongtien dvt="usd">1200</tongtien> <!-- Kieu so va khong duoc nho hon 0 -->
                <chitiethoadon>
                    <sanpham> <!-- co nhieu san pham -->
                        <masp>lt01</masp>
                        <tensp>Laptop Macbook</tensp>
                        <gia>1200</gia> <!-- Kieu so va khong duoc nho hon 0 -->
                        <soluong>1</soluong> <!-- Kieu so va khong duoc nho hon 0 -->
                    </sanpham> 
                </chitiethoadon>
            </hoadon>
        </danhsachhoadon>
    </taikhoan>
</danhsachtaikhoan>

=== cantsaywisp1308/JavaAll/eclipe-workspace/Java/XML/demo session 2/accountList.xml
<?xml version="1.0" encoding="UTF-8"?>


<danhsachtaikhoan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="account.xsd">


    <taikhoan ngaysinh="1980-10-20" gioitinh="nam"> <!-- Ngay sinh kieu date, gioi tinh chon 1 trong 2 gia tri nam hoac nu -->
        <username></username> <!-- Co it nhat 6 ki tu, toi da 10 ki tu, co 2 thuoc tinh min, max -->
        <password></password> <!-- Co it nhat 6 ki tu, toi da 10 ki tu -->
        <danhsachhoadon>
            <hoadon mahd="hd01"> <!-- Ma hoa don co it nhat 4 ki tu va toi da 6 ki tu -->
                <tenhd>Hoa don 1</tenhd>
                <ngaylap dinhdang="yyyy-MM-dd"></ngaylap> <!-- Kieu thoi gian co 1 thuoc tinh dindang -->
                <tinhtrang></tinhtrang> <!-- Chon 1 trong 2 gia tri: da thanh toan hoa chua thanh toan -->
                <httt></httt> <!-- Chon 1 trong 3 gia tri: tien mat, chuyen khoan hoac paypal -->
                <tongtien dvt="usd"></tongtien> <!-- Kieu so va khong duoc nho hon 0 -->
                <chitiethoadon>
                    <sanpham> <!-- co nhieu san pham -->
                        <masp></masp>
                        <tensp></tensp>
                        <gia></gia> <!-- Kieu so va khong duoc nho hon 0 -->
                        <soluong></soluong> <!-- Kieu so va khong duoc nho hon 0 -->
                    </sanpham> 
                </chitiethoadon>
            </hoadon>
        </danhsachhoadon>
    </taikhoan>
</danhsachtaikhoan>
