=== cantsaywisp1308/JavaAll/eclipe-workspace/Java/XML/demo session 2/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"></xs:element>
                <xs:element name="name" type="xs:string"></xs:element>
                <xs:element name="age" type="xs:int"></xs:element>
                <xs:element name="score" type="xs:double"></xs:element>
                <xs:element name="status" type="xs:boolean"></xs:element>
                <xs:element name="DOB" type="xs:date"></xs:element>
                <xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="address" type="address_type"></xs:element>
                <xs:element name="DOB2" type="type_dob_2"></xs:element>
                <xs:element name="age2" type="type_age_2"></xs:element>
                <xs:element name="gender" type="type_gender"></xs:element>
                <xs:element name="description" type="type_description"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="type_description">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"></xs:minLength>
            <xs:maxLength value="20"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="type_gender">
        <xs:restriction base="xs:string">
            <xs:enumeration value="male"></xs:enumeration>
            <xs:enumeration value="female"></xs:enumeration>
            <xs:enumeration value="other"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="type_age_2">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="18"></xs:minInclusive>
            <xs:maxInclusive value="60"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="type_dob_2">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="place" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"></xs:minLength>
                            <xs:maxLength value="20"></xs:maxLength>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="format" type="xs:string" use="optional"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="address_type">
        <xs:sequence>
            <xs:element name="street" type="xs:string"></xs:element>
            <xs:element name="ward" type="xs:string"></xs:element>
            <xs:element name="district" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== cantsaywisp1308/JavaAll/eclipe-workspace/Java/XML/demo session 2/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="student.xsd">
    <id>st01</id>
    <name>Alchemist</name>
    <age>20</age>
    <score>6.7</score>
    <status>true</status>
    <DOB>1993-08-13</DOB>
    <email>al@gmail</email>
    <email>alchemist@gmail</email>
    <email>alche@gmail</email>
    <address>
        <street>Truong Vinh Ky</street>
        <ward>Tan Thanh</ward>
        <district>Tan Phu</district>
    </address>
    <DOB2 place="Tan Phu" format="YYYY-MM-DD">1993-09-12</DOB2>
    <age2>60</age2>
    <gender>male</gender>
    <description>Money Maker</description>
</student>
